### ISSUE TITLE
How do you use this component ?

### ISSUE THREAD

**Issue by rockfight** [AndreasFaust/react-ticker#1]
I cannot understand from the example. Suppose I want to scroll content inside a `<div>` and I already have 20 contents that I want to scroll. How do I use it ?

**Comment by AndreasFaust** [comment]
The example-page for react-ticker is still a placeholder. A good documentation is in development. The whole project just started!
About your question: Are your content-elements static or do you want to load them from an API? 
Do you want to chain them or should only one element be visible at once?

**Comment by rockfight** [comment]
My elements are similar to stock ticker that will come from an API.

**Comment by AndreasFaust** [comment]
I'll provide you a working example today. 
I am working on the docs right now.
