### ISSUE TITLE
how to use this with a static array

### ISSUE THREAD

**Issue by Matthew-Cameron** [AndreasFaust/react-ticker#11]
Say I have an array that looks like the following {WFC, JNJ, MSFT, FB}. How do I properly get these array elements to render? 

Currently if I just put the array in a p tag, each Ticker element looks like: 
WFCJNJMSFTFB    WFCJNJMSFTFB    WFCJNJMSFTFB......

If I do a map on each array element and render each map element in a p tag. It creates an entire new Ticker row. ex:
WFC    WFC    WFC....
JNJ    JNJ    JNJ....
MSFT    MSFT    MSFT    MSFT......
FB    FB    FB    FB.......

How do I get it to look like this:
WFC   JNJ   MSFT   FB   WFC   JNJ   MSFT   FB   WFC   JNJ   MSFT   FB......

**Comment by ololoepepe** [comment]
Please post a minimal snippet so we can see what's going on.

**Comment by Matthew-Cameron** [comment]
Hi, thanks for the quick response.
First p tag corresponds to the first example above, and the commented code corresponds to the second example above. I understand why the map is rendering multiple Ticker rows. What I am after I feel like definitely corresponds to the uncommented portion.

props.account.getSymbols() = {WFC, JNJ, MSFT, FB}

`<Ticker className="stockSlider" speed={2}>
            {(index) => (
                <p className="stockSliderTicker">{props.account.getSymbols()}</p>
                
                // props.account.getSymbols().map(symbol => (
                //     <p className="stockSliderTicker">{symbol}</p>
                // ))
            )}
</Ticker>`

**Comment by ololoepepe** [comment]
So, I think you should do something like this:

```
const symbols = props.account.getSymbols();

//...

<Ticker className="stockSlider" speed={2}>
  {
    (index) => (
      <p className="stockSliderTicker">{[index % symbols.length]}</p>
    )
  }
</Ticker>
```

As stated in the README, "React Ticker calls its function-as-child anytime it runs out of content." That means, like, it says: "I need more stuff to render, please give me something", and you should provide the next element then.
The `index` is incremented continuously. If you do the `index % symbols.length` trick, the result will always be in the `[0, symbols.length)` interval (upper bound excluded), which is actually what you need, if I understood you correctly.

**Comment by barun1997** [comment]
@ololoepepe  Thanks for your response! Exactly what I needed. I just wanted to quickly point out, you should include (index) in curly brackets: ( {index} ) for it to work.

**Comment by Matthew-Cameron** [comment]
@barun1997 Hey would you mind showing me exactly what you did? I cant get it to work no matter what I do.

**Comment by barun1997** [comment]
Hi @Matthew-Cameron , sorry for the late reply. 

I implemented what @ololoepepe  suggested. 

For instance, if my array is: 

```
const news = [
  'ab',
  ' bc',
  ' cd !! '
];

```

**I implemented the following in my React function:** 


```
function App() {
  return (
    <div className="App">
      <Ticker speed={5} > 
      {
    ( {index} ) => (
      <div>
      <h1> {news[index % news.length]}   </h1>
      </div>
    )
  } 
  </Ticker>
    </div>
  );
}
```

I desired the following effect in my implementation: 

![Works](https://user-images.githubusercontent.com/19339044/74645189-8e767800-519f-11ea-8b34-9b1ce7177e3d.gif)


Do let me know if you have any questions!

**Comment by Matthew-Cameron** [comment]
@barun1997 Thank you so much!! This is exactly what I had but adding in the curly brackets around index made it work! I had given up on it but it now is working like a thing of beauty!

@ololoepepe Thanks for the help! I love what you have made!
