### ISSUE TITLE
Using Ticker with dynamic data.

### ISSUE THREAD

**Issue by suraj-kawale-au2** [AndreasFaust/react-ticker#12]
Here I have tried to implement react-ticker using dynamic data of some cryptos. But for some reason, it doesn't move. If I give it a fixed width then only it moves but overlaps some values. For that, I have to adjust the width for every new update in API. Is there some way to solve this? 

codesandbox : https://codesandbox.io/s/funny-night-kshog
output : https://kshog.csb.app/

**Comment by AndreasFaust** [comment]
Just take this example as a starting point and it will work.

```jsx
const GetRatesFromAPI = () => {
  const [rates, setRates] = useState("");
  useEffect(() => {
    async function fetchData() {
      const ratesFromAPI = await makeAPICall();
      setRates(ratesFromAPI);
    }
    fetchData();
  }, []);
  // A placeholder is needed, to tell react-ticker, that width and height might have changed
  // It uses MutationObserver internally
  return rates ? (
    <p style={{ whiteSpace: "nowrap" }}>{rates.join(" +++ ")} +++ </p>
  ) : (
    <p style={{ visibility: "hidden" }}>Placeholder</p>
  );
};

function StockTicker() {
  return (
    <Ticker offset="run-in" speed={10}>
      {() => <GetRatesFromAPI />}
    </Ticker>
  );
}

export default StockTicker;
```

**Comment by suraj-kawale-au2** [comment]
I have seen this example everywhere and tried it several times. But doesn't work.

**Comment by AndreasFaust** [comment]
Replace the empty `div` in TickerItems by `<p style={{ visibility: "hidden" }}>Placeholder</p>` and it will work.

**Comment by suraj-kawale-au2** [comment]
Yes. It worked. But how?

**Comment by AndreasFaust** [comment]
It has to do with the `Mutation Observer`, which seemingly does not work with empty `divs`.

**Comment by AndreasFaust** [comment]
When the elements are loaded, the observed element is changed and the width of this changed element is calculated. `react-ticker` observes when this element will be vanishing from the viewport and calls the function, which generates a new placeholder, which will be replaced by loaded elements and so on.

**Comment by AndreasFaust** [comment]
If this answer and `react-ticker` are helpful for you, please consider supporting my open-source-work by staring this library. Have a nice day!
