### ISSUE TITLE
last element stay => after reload bug is fixed

### ISSUE THREAD

**Issue by martellapetesso** [AndreasFaust/react-ticker#16]
Hello everybody,

i have the problem that on the first start, the last element stay. After i reload the screen or switch the tabs, the bug is away and all is perfect. (look the gif)

![react-ticker-bug](https://user-images.githubusercontent.com/48688668/76616318-0d06d100-6524-11ea-9510-b628f4cd4a88.gif)

**Comment by AndreasFaust** [comment]
Hello! Please provide a CodeSandbox to reproduce the error.
https://codesandbox.io/

**Comment by martellapetesso** [comment]
Unfortunately i cant reproduce the error:

[CodeSandBox](https://codesandbox.io/s/old-leaf-7n7r2)

in this case it work well. And it is exactly the same code only with other icons. Any idea what it can be?

**Comment by AndreasFaust** [comment]
Try to set the ticker-container to `overflow: hidden;`.

**Comment by AndreasFaust** [comment]
If this answer and react-ticker are helpful for you, consider supporting my open-source work by giving this library a star.

**Comment by martellapetesso** [comment]
Dont work with overflow: hidden. Nevertheless the star is given.

**Comment by AndreasFaust** [comment]
Thank you very much! 
Which `react`-version and which dev-environment do you use? 
Have you tried to render a `production` build and checked whether the problem persists?

The bug must originate from a very special configuration. The library has been downloaded 45.000 times and this is the first time we experience this bug.

**Comment by martellapetesso** [comment]
I have React Version 16.9. in my project. And yes i have tried as production build, same problem. I dont know what configuration it can be. I have wrapped the complete page in a Grid from Material ui. Is it possible, that this is the problem?

**Comment by AndreasFaust** [comment]
I assume, the problem originates from the container-width, which is not finally set when the ticker is initiated. Can you try to defer the ticker-initialisation by, let’s say, 1000 milliseconds?

But as long as we can’t reproduce the bug, I can just guess, unfortunately. Could you try setting up React 16.9, the Material-Grid, as well as your original Image-Sources in the Sandbox to hopefully create a valid test-case?

**Comment by martellapetesso** [comment]
It works when i defer the ticker-initialisation with 500 ms. Thank you very much!

I have in the CodeSandBox now exactly the same dependencies and the same layout with material ui grid and so on. The versions are also the same.

**Comment by AndreasFaust** [comment]
But the bug does not show up in the Sandbox, doesn’t it? 
At least we seem to know now, that the bug originates from a parent component, that takes some time to initialize and render, which interrupts the rendering of the ticker. 

I would now remove one parent component after another, trying to isolate the bug source. And after that you will have to find an event or callback, to initialize the ticker when the parent is ready. Or you skip all that and just stick to the timeout, if it works. Life is short and code never works perfectly.

**Comment by martellapetesso** [comment]
Yes it doesn´t show the bug in Sandbox. Yeah you are right. Let us close the issue. And thanks for the component.

**Comment by AndreasFaust** [comment]
You’re welcome!
