### ISSUE TITLE
Rendering an array, I want ticker to show one content at a time.

### ISSUE THREAD

**Issue by mikel-js** [AndreasFaust/react-ticker#18]
Hi, here is my code

function FactsTicker() {
  const updates = [
    { info: "1" },
    { info: "2" }
  ]
  return (
    <>
      <h3 style={{ color: 'black' }}>Did you know?</h3>
      <Ticker mode='await' speed={20} offset="run-in" style={{width: '100%', overflow: 'hidden'}}>
        {() => (
          <>
            <h5>
              {updates.map((update) => (
                 {update.info}
              ))}
            </h5>
          </>
        )}
      </Ticker>
    </>
  )
}

I want to show elements one at a time, so after "1" has passed, then "2" will appear. 

WHat is happening in the code above is = 
 12                          12                            12. 

When I tried putting the map() method before the Ticker, then it has 2 columns and appears at the same time, like
1                             1                                 1
2                             2                                 2

**Comment by PraveenRanjan** [comment]
Hi, DId you get a solution for this problem?

**Comment by PraveenRanjan** [comment]
I found the solution:

I wrote a method that returns only one item from the list at a time. Used state to check and reset if list reach to last element. See my solution here:

import React, { useState } from "react";
import Ticker from "react-ticker";
import PropTypes from "prop-types";

const TickerComponent = props => {
const [count, setCount] = useState(0);
const getNewsItem = () => {
if (count < props.data.length - 1) {
console.log("befor calling setCount ", count);
setCount(count + 1);
console.log("count after::", count);
} else {
setCount(0);
}
const item = props.data[count];

return (
  <>
   
    <span>
      {item.Description + " count::" + count}
    </span>
  </>
);
};

return (

{() => getNewsItem()}

);
};

TickerComponent.propTypes = {
data: PropTypes.array
};

export default TickerComponent;

**Comment by mikel-js** [comment]
> I found the solution:
> 
> I wrote a method that returns only one item from the list at a time. Used state to check and reset if list reach to last element. See my solution here:
> 
> import React, { useState } from "react";
> import Ticker from "react-ticker";
> import PropTypes from "prop-types";
> 
> const TickerComponent = props => {
> const [count, setCount] = useState(0);
> const getNewsItem = () => {
> if (count < props.data.length - 1) {
> console.log("befor calling setCount ", count);
> setCount(count + 1);
> console.log("count after::", count);
> } else {
> setCount(0);
> }
> const item = props.data[count];
> 
> return (
> <>
> 
> ```
> <span>
>   {item.Description + " count::" + count}
> </span>
> ```
> 
> </>
> );
> };
> 
> return (
> 
> {() => getNewsItem()}
> 
> );
> };
> 
> TickerComponent.propTypes = {
> data: PropTypes.array
> };
> 
> export default

Hi Praveen, yes, I found the solution, almost similar as yours. Thank you anyways.
