### ISSUE TITLE
resizing causes full crash with typeError: Cannot read properties of null (reading 'height')

### ISSUE THREAD

**Issue by codyscott1** [AndreasFaust/react-ticker#33]
it takes quite a bit of resizing to get this to crash but eventually it happens. 
![image](https://user-images.githubusercontent.com/58891378/140660725-caf8f3a9-71c6-44a5-ab8d-dd7b9c277368.png)
ticker code is [here](https://github.com/Shopify/hydrogen-examples/blob/master/shopify_supply/src/components/TickerTape.client.jsx)
setting a hardcoded height param _may_ fix it but I need the ticker to resize on different screen sizes. Ideas?

**Comment by i3web** [comment]
I have the same problem。

**Comment by codyscott1** [comment]
@AndreasFaust I have a fix for this. I can add a PR if you can give me access please.

if you would rather add it I think changing line 4 in `getHighest.js` from
```  if (el.rect.height > highest) {```
to
```  if (el.rect && el.rect.height > highest) {```
would do the trick

**Comment by codyscott1** [comment]
resolved in https://github.com/AndreasFaust/react-ticker/pull/35
