### ISSUE TITLE
react-ticker not rendering data untill component height is not changed.

### ISSUE THREAD

**Issue by rajgohel** [AndreasFaust/react-ticker#34]
react-ticker not rendering data untill component height is not changed.
Kindly check below screenshots.

Before resize component
![TickerBefore](https://user-images.githubusercontent.com/42000751/141127258-7ddc83db-6c7e-4563-892e-b1aa9b3260bf.png)
After resize component
![TickerAfter](https://user-images.githubusercontent.com/42000751/141127277-01c47ee3-0252-470f-8dda-5ca34d5c3a08.png)

**Comment by rajgohel** [comment]
I have whole component after data retrieved before that i have loaded partial component now it is working as aspected.

**Comment by premtemp1** [comment]
@rajgohel 
I know this is an old issue but I am having similar problem. The widget only shows if the window is resize. Did you find a solution?
