### ISSUE TITLE
Issue dynamically changing direction

### ISSUE THREAD

**Issue by mckelveygreg** [AndreasFaust/react-ticker#4]
Hey! 
This is so close to the solution I need, but I'm having trouble. I have `<Ticker move={move} direction={direction}>` set with dynamic direction and move props that are changed by hover events. Starting and stopping work great, but when it changes direction, the whole ticker starts over instead of just changing direction. 

Is that something this can do?

**Comment by AndreasFaust** [comment]
Hello! Without further investigation I would say: I'm afraid it can't. I've built it for a job, which did not need this flexibility. But give me a little time, to see what I can do.

**Comment by mckelveygreg** [comment]
Thanks for getting back to me! (I'm currently trying to get something working for a job 💯 ) I was hoping it would just be a +=/-= type thing... But I'm not sure how you make it loop so well! 
Regardless, thanks for posting things you've built for others to use/look at!!

**Comment by AndreasFaust** [comment]
The code was build without the blessings of context and hooks, so it looks rather verbose. It animates every element seperately, which I don't know, if that's a good idea: theoretically it brings more flexibility, but is also much more complex to observe, than putting the elements into a wrapper and animate this.
