### ISSUE TITLE
Cant render Ticker

### ISSUE THREAD

**Issue by joebentaylor** [AndreasFaust/react-ticker#5]
index.es.js:289 Uncaught TypeError: _this.props.children is not a function

this is my code:
`<Ticker>
                    {this.props.logos.map((block) => (
                        <Logo key={block.id}>
                            <img src={block.url} alt={block.alt} />
                        </Logo>
                    ))}
</Ticker>`

**Comment by AndreasFaust** [comment]
You need to render a function-as-child. 
Try this (not tested):
``
<Ticker> 
  {() => (
    this.props.logos.map(block => ( 
      <Logo key={block.id}>
        <img src={block.url} alt={block.alt} />
      </Logo>
    )
  )} 
</Ticker>
``
