### ISSUE TITLE
Resizing screen with long string causes multiple lines

### ISSUE THREAD

**Issue by milehighhokie** [AndreasFaust/react-ticker#8]
First - Nice job on this!  I feel bad for being whiny 

Now to pour the whine...
If I start with a large screen and a large string (over 100 characters) and then resize the screen to be smaller, then text then appears on multiple lines.  Additionally, if height is specified, you might not see the extra lines if they are beyond the space you requested.

![Untitled](https://user-images.githubusercontent.com/7454436/63225885-cff77d80-c192-11e9-8c85-27494ff2ee82.png)

**Comment by AndreasFaust** [comment]
Thank you! Have you tried to set `white-space: nowrap;` on the text-container? 
Additionally I have to admit, that resizing is not handled ideally. I've created this project for a job and the status quo was just good enough in this context.

**Comment by milehighhokie** [comment]
<h1 style={{ whiteSpace: "nowrap" }}> did the trick!  Thank you for the work and the quick response.  I'll close this since that is a working solution.
